//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.07 at 04:58:48 PM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.cdisc.org/ns/odm/v1.3", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cdisc.ns.odm.v130;
